import { Metadata } from 'next';
import DailiesScreen from '@/screens/DailiesScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

export default function Dailies() {
	return <DailiesScreen />;
}
