import { Metadata, NextPage } from 'next';
import DailiesScreen from '@/screens/DailiesScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

const Dailies: NextPage = () => {
	return <DailiesScreen />;
};

export default Dailies;
