import { Metadata, NextPage } from 'next';
import WordsScreen from '@/screens/WordsScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

const Words: NextPage = () => {
	return <WordsScreen />;
};

export default Words;
