import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../../components/Header';
import StyledComponentsRegistry from './registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Flo does not (yet) exist',
	description: 'Generated by a computer; displayed on a screen.',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<StyledComponentsRegistry>
				<body className={inter.className}>
					<Header />
					{children}
				</body>
			</StyledComponentsRegistry>
		</html>
	);
}
