import { Metadata } from 'next';
import HomeScreen from '@/screens/HomeScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

export default function Home() {
	return <HomeScreen />;
}
