import { Metadata, NextPage } from "next";
import { Hero } from "@/components/ui/Hero";
import Feed from "@/components/Feed";
import { dailies } from "../../content/dailies";

export const metadata: Metadata = {
  title:
    "Collection feed of random things, thoughts, images, drawings, snippets, shorts and ideas",
  description: "Generated by a computer; displayed on a screen.",
};

const Home: NextPage = () => {
  return (
    <>
      <Hero />
      <Feed dailies={dailies} />
    </>
  );
};

export default Home;
