import { Metadata, NextPage } from 'next';
import DailiesScreen from '@/screens/DailiesScreen';

export const metadata: Metadata = {
	title:
		'Collection feed of random things, thoughts, images, drawings, snippets, shorts and ideas',
	description: 'Generated by a computer; displayed on a screen.',
};

const Home: NextPage = () => {
	return <DailiesScreen />;
};

export default Home;
