import { Metadata, NextPage } from 'next';
import VisualsScreen from '@/screens/VisualsScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

const Visuals: NextPage = () => {
	return <VisualsScreen />;
};

export default Visuals;
