import { Metadata } from 'next';
import VisualsScreen from '@/screens/VisualsScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

export default function Visuals() {
	return <VisualsScreen />;
}
