import { Metadata, NextPage } from 'next';
import MusicScreen from '@/screens/MusicScreen';

export const metadata: Metadata = {
	title: 'Flo does partly exist',
	description: 'Generated by a computer; displayed on a screen.',
};

const Music: NextPage = () => {
	return <MusicScreen />;
};

export default Music;
